name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore and export service account to ENV for GCS remote cache
        run: |
          echo $GCS_SERVICE_ACCOUNT > service.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=service.json" >> $GITHUB_ENV
        if: env.GCS_SERVICE_ACCOUNT
        env:
          GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}
      
      # Upload
      - name: Create dummy file
        run: echo "Dummy file ${{ github.run_number }}" > skw_dummy.txt
      - uses: ./skw
        with:
          skw-version: v0.2.0
          command: upload
          bucket: gs://kesin11_bazel_cache
          key: actions-skw-skw
          tags: |
            ${{ github.run_number }}
            latest
          prefix: skw
          paths: |
            skw_dummy.txt

      # Download
      - uses: ./skw
        with:
          skw-version: v0.2.0
          command: download
          bucket: gs://kesin11_bazel_cache
          key: actions-skw-skw
          tags: ${{ github.run_number }}
          paths: ./download
      
      - name: Vefiry download file
        run: cat download/skw/skw_dummy.txt
      
